spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/Jerry/Documents/workspace/cloud-baseline/config/src/main/resources/share
  profiles:
     active: native
  application:
    name: config

server:
  port: 8888